name: Check if image needs rebuilding for updates

on:
  workflow_dispatch

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.version_finder.outputs.latest_version }}
      current_version: ${{ steps.version_loader.outputs.current_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install -y curl
          sudo apt-get install -y wget
          sudo apt-get install -y xmlstarlet
      - name: Find latest InteliJ version
        id: version_finder
        run: |
          curl --silent 'https://www.jetbrains.com/updates/updates.xml' > jetbrainsUpdates.xml
          xmlstarlet sel -t -v '//product[@name="IntelliJ IDEA"]/channel[@name="IntelliJ IDEA RELEASE"]/build/@version' jetbrainsUpdates.xml > IDEAVersions
          LATEST_VERSION=$(build_scripts/latest_version IDEAVersions)
          echo "Latest InteliJ version is ${LATEST_VERSION}"
          echo "latest_version=${LATEST_VERSION}" >> "$GITHUB_OUTPUT"
      - name: Load current InteliJ version
        id: version_loader
        run: |
          CURRENT_VERSION='0.0.0'
          if [[ -f IDEAVersion ]]; then
            CURRENT_VERSION=$(cat IDEAVersion)
          fi
          echo "Current InteliJ version ${CURRENT_VERSION}"
          echo "current_version=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"
  commit-new-idea-version:
    needs: get-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit updated InteliJ version number
        if: ${{ needs.get-versions.outputs.latest_version != needs.get-versions.outputs.current_version }}
        env:
          LATEST_VERSION: ${{ needs.get-versions.outputs.latest_version }}
          COMMIT_EMAIL: ${{ secrets.GIT_COMMIT_EMAIL }}
        run: |
          echo "${LATEST_VERSION}" > IDEAVersion
          git config user.name github-actions
          git config user.email "${COMMIT_EMAIL}"
          git add IDEAVersion
          git commit -m "Update to InteliJ version ${LATEST_VERSION}"
          git push
      - name: Skipping committing new version
        if: ${{ needs.get-versions.outputs.latest_version == needs.get-versions.outputs.current_version }}
        run: |
          echo 'No new IntelliJ version to commit'
  check-package-upgrades:
    runs-on: ubuntu-latest
    outputs:
      package_upgrade_count: ${{ steps.upgrade_test.outputs.upgradeable }}
    steps:
      - name: Test latest container for package upgrades
        id: upgrade_test
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          SIMULATED_UPGRADE_RESULTS=$(docker run --tty --rm ${{ secrets.DOCKERHUB_USERNAME }}/d-idea:latest sh -c 'apk update && apk --update-cache upgrade --simulate')
          UPGRADEABLE_PACKAGES=$(echo ${SIMULATED_UPGRADE_RESULTS} | grep --only-matching 'Upgrading' | wc -l)
          if [[ "${UPGRADEABLE_PACKAGES}" -eq 0 ]]; then
            echo '[INFO] No packages detected as upgradable'
          else
            echo "[INFO] Detected ${UPGRADEABLE_PACKAGES} packages that can be upgraded"
          fi
          echo "upgradeable=${UPGRADEABLE_PACKAGES}" >> "$GITHUB_OUTPUT"
  trigger-image-build:
    needs: [commit-new-idea-version, check-package-upgrades]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger image build workflow
        if: ${{ needs.get-versions.outputs.latest_version != needs.get-versions.outputs.current_version || needs.check-package-upgrades.package_upgrade_count > 0 }}
        run: |
          echo '[DEBUG] Should now call build image workflow'
      - name: No need to build
        if: ${{ needs.get-versions.outputs.latest_version == needs.get-versions.outputs.current_version && needs.check-package-upgrades.package_upgrade_count == 0 }}
        run: |
          echo '[INFO] InteliJ version already latest and no packages to upgrade - NOT rebuilding image'
