name: Build and push Docker image

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  buid-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Dockerhub
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u "${USERNAME}" -p "${PASSWORD}"
      - name: Build image
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          INTELLIJ_VERSION=$(cat IDEAVersion)
          echo "[INFO] Building d-idea image for Intelij version ${INTELLIJ_VERSION}"
          docker build  --build-arg "INTELLIJ_VERSION=${INTELLIJ_VERSION}" --tag "${USERNAME}/d-idea:latest" .
      - name: Push image
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push "${USERNAME}/d-idea:latest"
