name: Main branch CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'

jobs:
  build-image:
    uses: ./.github/workflows/build-image.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}